
### Get all users
GET http://localhost:3000/api/users
Content-Type: application/json
X-Tenant-ID: tenant3

###

### Get a single user by ID
GET http://localhost:3000/api/users/67f7cebfcce22fa3fbdde7b4
Content-Type: application/json
X-Tenant-ID: tenant1

###

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json
X-Tenant-ID: tenant1

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

###

### Update a user by ID
PUT http://localhost:3000/api/users/67f7cebfcce22fa3fbdde7b4
Content-Type: application/json
X-Tenant-ID: tenant1

{
  "name": "John Doe Updated",
  "email": "john.doe.updated@example.com",
  "password": "newpassword123"
}

###

### Delete a user by ID
DELETE http://localhost:3000/api/users/67f7cebfcce22fa3fbdde7b4
Content-Type: application/json
X-Tenant-ID: tenant1
